version: "3.9"
services:
  api:
    image: 665860285991.dkr.ecr.us-east-2.amazonaws.com/url-shortner:0b34de48f9dfc2c1b4b13a07eb70419528ce7fd1
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database

  database:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
