version: "3.9"
services:
  api:
    image: url-shortner
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database

  database:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
